SimSettings: Port manual SIM provisioning support
commit 1751f6f3fcdce02c56ecfed89cb84c4f632baa4a
Author: Danny Baumann <dannybaumann@web.de>
Date:   Thu Feb 16 14:50:56 2017 +0100

    Fix possible NPE on SIM settings shutdown.

    Change-Id: Ibf6b54fc2b97a780cfd7ace17c54855ef7e70c57

commit f982e03c0074ef953a21dda772fa56e19399fb46
Author: Danny Baumann <dannybaumann@web.de>
Date:   Tue Feb 28 12:26:37 2017 +0100

    Clean up SIM enable toggle implementation

    - Move strings to cm_strings.xml
    - Improve string wording
    - Remove unused code
    - Streamline implementation

    Change-Id: I58fc3002cfcc37dd1798819223289cc541bed211

commit 7adcacb2b7b586f2cc1fe26db769e63553a89494
Author: Ricardo Cerqueira <ricardo@cyngn.com>
Date:   Thu Jul 28 12:29:40 2016 +0100

    SimSettings: Make provisioning optional even if qti-telephony is present

    Current code assumes the manual provisioning options should come
    up if the qti-telephony blob is present. Don't make that assumption.

    Change-Id: I5e4f28b628e3fe3fe9e506631e92c85103e87ccf

commit bdc7782bceb1dfe27996aa4be6bdbae865777aaa
Author: Venkatraman Nerellapalli <venkataraman.nerellapalli@codeaurora.org>
Date:   Sat Jan 9 17:20:00 2016 +0530

    Telephony(MSIM): Fix ANR on SIM deactivation

    Dismiss dialog box on confirmation.
    SIM activation & deactivation in background thread.

    Change-Id: I0268a710f35e30b2abec3dd671942b52fc0e0b46
    CRs-Fixed: 957308

commit e7f94ba9a879bd0928efade6ed3734eb829ed834
Author: Luca Stefani <luca.stefani.ge1@gmail.com>
Date:   Sun Jul 3 21:56:08 2016 +0200

    Settings: Disable sim switch if subscription isn't valid

    Change-Id: I22ba9a3270da13f77fdd43586b7dc487f0929453

commit c6856615eb456139108570dc855356e0cb95ab7c
Author: LuK1337 <priv.luk@gmail.com>
Date:   Sun Jul 3 22:11:26 2016 +0200

    Settings: Don't set the icon for sim activation / deactivation dialog

    * This icon doesn't look any good.
      It's better to just get rid of it.

    Change-Id: I47f70a80136695e9aa61ff98999a2cf770390079

commit 9e21654c1d8f3393cfb662866b64e3531645e31b
Author: LuK1337 <priv.luk@gmail.com>
Date:   Sun Jan 3 22:32:00 2016 +0100

    Hide manual provisioning switch when extphone framework is not present

    * It doesn't work without it.

    Change-Id: Iec11ec2006059f26668f2a6fee4c2c9ca6650119

commit 00823fa8f1f91da538440425e676b95b4d829457
Author: Ricardo Cerqueira <ricardo@cyngn.com>
Date:   Thu Nov 5 18:23:52 2015 +0000

    Break MSIM dependency on qci-telephony-framework

    If the provisioning state is invalid, the framework is most likely
    absent. Consider the card as provisioned to pass all relevant checks.

    Change-Id: I975ff156e4328e9d3f6e2626a863bbacb29e3337

commit e92619a138fc1a2370ed0d583bae0573c214eaf0
Author: Sandeep Gutta <sangutta@codeaurora.org>
Date:   Mon Sep 14 20:14:07 2015 +0530

    Telephony(MSIM): Select preferred primary sub.

    Add UI to select preferred primary sub.
    It is used when two SIM cards inserted have same
    priority as per policy.

    Change-Id: I5726fe9f4df03e680dc2406854d08da77297444d

commit dade627ff0569117908a5ef47f93251530c6f319
Author: Sandeep Gutta <sangutta@codeaurora.org>
Date:   Sun Sep 13 22:09:23 2015 +0530

    Telephony(MSIM): Fix to do not allow both SIM deactivation

    Use proper SubInfo record object to do not allow
    user to deactivate both SIMs on DSDS devices.

    Change-Id: I6f56d819367272b3a009c7a8133709c643e8bd84
    CRs-Fixed: 893504

commit d9983cb15c59672f3030869a6b5f143da5320866
Author: Sandeep Gutta <sangutta@codeaurora.org>
Date:   Mon Aug 10 15:09:59 2015 +0530

    Telephony(MSIM): Manual provision related fixes

    - Consider Manual provision state while displaying
      active sub info list.
    - Enable sms/data user preference option only
      if more than one subscription active.
    - Introduce below system proeprty to control AOSP
      behavior of user selection of fallback preference
      for sms/data
      "persist.radio.aosp_usr_pref_sel"

    Change-Id: I2b308b801f3f677c5a3ffaee5a8e6beda12aedd2

commit 86b04f6dfd56383bc0142cb5d03ebca9648b5061
Author: Chaitanya Saggurthi <csaggurt@codeaurora.org>
Date:   Thu Jul 16 16:33:34 2015 +0530

    Telephony(MSIM): Add Manual provisioning support

    Add toggle switch UI option in SimSettings screen to
    enable/disable SIM cards

    Change-Id: Id07271aedb12eabc0b106ac278ba2e12c71cfe03

commit a19413ea1f917bbf6f3e9ae61c85ae08d7950d50
Author: xyyx <xyyx@mail.ru>
Date:   Sat Jan 20 14:36:50 2018 +0800

    Vectorize ic_live_help icon and fix theming for SimDialogActivity

    Change-Id: I86d1bfdb2120a53bf1dcd21181ecdf2bd9e663e8

commit 4052460b29a64b7f8fc3b0e88c5a2f7036cc222d
Author: xyyx <xyyx@mail.ru>
Date:   Sat Jan 20 12:30:44 2018 +0800

    Fix MultiSim hardcoded text color

    Change-Id: If2ff79f76c90437a73b05f102f65c564004455b9

commit 8e62fc50dc327889ebe6c4ca1725b4db0db56f58
Author: Bruno Martins <bgcngm@gmail.com>
Date:   Tue Jun 5 18:51:25 2018 +0100

    SimSettings: Use TelephonyExtUtils helper methods

    PE edits: Use telephony-common api

    Change-Id: Id6eaffffb3c2b2b2dead36e0f56d8547e6188690
    Signed-off-by: Henrique Silva <jhenrique09.mcz@hotmail.com>

:...skipping...
commit a19413ea1f917bbf6f3e9ae61c85ae08d7950d50
Author: xyyx <xyyx@mail.ru>
Date:   Sat Jan 20 14:36:50 2018 +0800

    Vectorize ic_live_help icon and fix theming for SimDialogActivity

    Change-Id: I86d1bfdb2120a53bf1dcd21181ecdf2bd9e663e8

commit 4052460b29a64b7f8fc3b0e88c5a2f7036cc222d
Author: xyyx <xyyx@mail.ru>
Date:   Sat Jan 20 12:30:44 2018 +0800

    Fix MultiSim hardcoded text color

    Change-Id: If2ff79f76c90437a73b05f102f65c564004455b9

commit 8e62fc50dc327889ebe6c4ca1725b4db0db56f58
Author: Bruno Martins <bgcngm@gmail.com>
Date:   Tue Jun 5 18:51:25 2018 +0100

    SimSettings: Use TelephonyExtUtils helper methods

    PE edits: Use telephony-common api

    Change-Id: Id6eaffffb3c2b2b2dead36e0f56d8547e6188690
    Signed-off-by: Henrique Silva <jhenrique09.mcz@hotmail.com>

commit e5bcc4ea079bd49f014d5bdde2476b23e17d3269
Author: Michael W <baddaemon87@gmail.com>
Date:   Thu May 31 14:11:34 2018 +0200

    SimSettings: Fix preferred calls sim not being disabled

    * When disabling a sim on a dual sim device, the selection
      would not be disabled properly

    Change-Id: Ib8054f724ae974640491d03c668066db47b8a3a9

commit 1ec24e0469816fbfd67ac051c55d2ebd10d4cf61
Author: LuK1337 <priv.luk@gmail.com>
Date:   Thu May 10 13:52:45 2018 +0200

    SimSettings: Fix potential NPE

    * A non-null phoneAccount reference doesn't guarantee a valid
      PhoneAccount is being returned from TelecomManager
    * While we're at it, fix indentation for phoneAccount
      and allPhoneAccounts

    Change-Id: I49490d6382034ed92bc5d8f1ea3782229482c7a9

commit 141e5b3a8210b6c006bd9e964915f63977bbf627
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Jan 26 18:39:50 2018 +0100

    SimSettings: Handle NoClassDefFoundError on devices without telephony-ext

    Change-Id: I9f4a2c773d8ad1d82993ea19bf9ee5e70e5d0516

commit 3cfbfb2675bdcca816676caa941a7f62e04b9011
Author: Umashankar Godachi <umasha@codeaurora.org>
Date:   Fri Jan 8 19:54:43 2016 +0530

    MSIM: Fix user set DDS sub in hotswap cases.

    Currently if user set DDS sim is removed and inserted,
    dds will not fallback to user preferred sub.

    Fix: Save the user preferred DDS sub in DB and set it
    as DDS sub, when sim is removed and inserted.

    Change-Id: Ic34fdbad70a7dc99a0fa5de9cbb9d24caa6bac87
    CRs-Fixed: 958445

commit 41ca83e2d6297f737036c2f4ba3d985dea644007
Author: maxwen <max.weninger@gmail.com>
Date:   Sat Jan 20 13:39:17 2018 +0100

    SimSettings: Improve dialogs

    Squash of:

    Settings: no need to show a success alert dialog on sim switch

    very 'un-android-like' :)

    Change-Id: Ie68eed174464d7acf67171a509a19045e0d9c669

    Settings: fix neverending progress on sim activation change

    what a stupid bug....

    and while we are here - also the confirm dialog on
    deactivation is actually useless - using the switch
    should be more enough to not always ask and anoy user
    if he really knows what he is doing

    Change-Id: I38eb17cf8d12259f34b339da2ad807d12a5c0d41

commit b75d80e44bb623c2a4f0b514483b115b975d5046
Author: xyyx <xyyx@mail.ru>
Date:   Fri Jan 19 23:31:36 2018 +0800

    SimSettings: Correctly disable sim switch without SIM card

    * Code extracted from MM CAF

    Change-Id: I59924806302c57e5652b18235e50c9569153dbd3

commit 9870e115f7587401ea7c792317d35beaefa3006e
Author: Alex <alex@dirtyunicorns.com>
Date:   Sat Jul 7 23:56:45 2018 -0500

    Fix multi-sim dialog in RTL

    No better way to explain the fail than with pictures

    Before - https://i.imgur.com/mr5MphQ.png
    After - https://i.imgur.com/XsfnEPz.png

    Test:
    - Enable RTL
    - Go into Settings/Network & Internet/SIM cards
    - Select any SIM slot

    Change-Id: I12d9e45ae3a2edfc670f551174ef5e064297af64

Change-Id: I877ed2511ee01868f68146dbd241faedd938033b